stages:
  - test
  - deploy

tests:
  image: python:3.10
  before_script:
    - pip install -r requirements.txt
  script:
    - ./manage.py test


deploy:
  tags:
    - infra
  stage: deploy
  script:
    - docker build -t league:latest .
  only:
    - master

