stages:
  - test
  - package
  - rollout

tests:
  stage: test
  image: python:3.10
  before_script:
    - pip install -r requirements.txt
  script:
    - ./manage.py test

python-format:
  stage: test
  image: python:3.10
  before_script:
    - pip install black
  script:
    - black --check --verbose .

build-docker:
  stage: package
  only:
    refs:
      - master
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo $CI_COMMIT_SHORT_SHA > commit_sha.txt
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$CI_HUB_SECRET\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination antoinealb/league:latest

restart-service:
  stage: rollout
  only:
    refs:
      - master
  tags:
    - infra
  script:
    - sudo /bin/systemctl restart league.service
