stages:
  - test
  - package
  - rollout

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: pipcache
  paths:
    - .cache/pip

tests:
  stage: test
  image: python:3.12
  before_script:
    - pip install --upgrade -r requirements.txt
  script:
    - ./manage.py test --testrunner "xmlrunner.extra.djangotestrunner.XMLTestRunner"
  artifacts:
    when: always
    reports:
      junit: TEST-*.xml

migrations:
  stage: test
  image: python:3.12
  before_script:
    - pip install --upgrade -r requirements.txt
  script:
    - ./manage.py makemigrations --check --dry-run

python-typing:
  stage: test
  image: python:3.12
  before_script:
    - pip install --upgrade -r requirements.txt
    - pip install --upgrade mypy
  script:
    - mypy --install-types --non-interactive championship invoicing

python-format:
  stage: test
  image: python:3.12
  before_script:
    - pip install -r requirements.txt
    - pip install pre-commit
  script:
    - pre-commit run --all-files

templates-format:
  stage: test
  image: python:3.12
  before_script:
    - pip install djhtml==1.5.2
  script:
    - djhtml --check championship/templates invoicing/templates

web-format:
  stage: test
  image: node:19
  before_script:
    - npm install prettier
  script:
    - npx prettier --check static


build-docker:
  stage: package
  only:
    refs:
      - master
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo $CI_COMMIT_SHORT_SHA > commit_sha.txt
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$CI_HUB_SECRET\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination antoinealb/league:latest

restart-service:
  stage: rollout
  only:
    refs:
      - master
  tags:
    - infra
  script:
    - sudo /usr/bin/docker pull antoinealb/league:latest
    - sudo /bin/systemctl restart league.service
    - sleep 30
    - sudo /usr/bin/docker exec league.service ./manage.py migrate --no-input
    - ./notify_deploy_on_grafana.sh
