# Generated by Django 4.1.3 on 2022-11-25 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                (
                    "url",
                    models.URLField(
                        help_text="A website for information, ticket sale, etc."
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("LEGACY", "Legacy"),
                            ("MODERN", "Modern"),
                            ("LIMITED", "Limited"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("100", "100"), ("250", "250"), ("500", "500")],
                        max_length=4,
                    ),
                ),
                (
                    "ranking_type",
                    models.CharField(
                        choices=[
                            ("ROUNDS", "Number of rounds"),
                            ("RANKED", "Ranking-based"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "round_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of rounds, only used for tournaments with fixed number of rounds.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventPlayerResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ranking",
                    models.IntegerField(
                        blank=True,
                        help_text="Ranking, for tournaments where a ranking result is used.",
                        null=True,
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of points, for fixed-rounds tournaments.",
                        null=True,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="championship.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "events",
                    models.ManyToManyField(
                        through="championship.EventPlayerResult",
                        to="championship.event",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="eventplayerresult",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="championship.player"
            ),
        ),
        migrations.CreateModel(
            name="EventOrganizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "contact",
                    models.EmailField(
                        help_text="Prefered contact email", max_length=254
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="championship.eventorganizer",
            ),
        ),
    ]
