# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 4.1.1 on 2022-12-07 13:13

from django.db import migrations

import django_bleach.models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0002_eventplayerresult_single_elimination_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=django_bleach.models.BleachField(
                blank=True,
                help_text="Supports the following HTML tags: a,abbr,acronym,b,blockquote,code,em,i,li,ol,strong,ul",
            ),
        ),
    ]
