# Generated by Django 4.1.1 on 2022-12-07 13:13

from django.db import migrations

import django_bleach.models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0002_eventplayerresult_single_elimination_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=django_bleach.models.BleachField(
                blank=True,
                help_text="Supports the following HTML tags: a,abbr,acronym,b,blockquote,code,em,i,li,ol,strong,ul",
            ),
        ),
    ]
