# Generated by Django 4.1.1 on 2022-12-07 13:17

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0003_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=django_bleach.models.BleachField(
                blank=True,
                help_text="Supports the following HTML tags: a, abbr, acronym, b, blockquote, code, em, i, li, ol, strong, ul",
            ),
        ),
    ]
