# Generated by Django 4.1.1 on 2022-12-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0005_alter_eventplayerresult_single_elimination_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventplayerresult",
            name="ranking",
            field=models.PositiveIntegerField(
                default=0, help_text="Standings after the Swiss rounds"
            ),
            preserve_default=False,
        ),
    ]
