# Generated by Django 4.1.1 on 2023-01-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0006_eventplayerresult_ranking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="A website for information, ticket sale, etc.",
                null=True,
                verbose_name="Website",
            ),
        ),
    ]
