# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 4.1.1 on 2023-01-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0007_alter_event_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="hidden_from_leaderboard",
            field=models.BooleanField(
                default=False,
                help_text="If true, this should be hidden from the global leaderboard. Useful for virtual players, such as Eventlink's REDACTED.",
            ),
        ),
    ]
