# Generated by Django 4.1.3 on 2023-02-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0008_player_hidden_from_leaderboard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="format",
            field=models.CharField(
                choices=[
                    ("LEGACY", "Legacy"),
                    ("LIMITED", "Limited"),
                    ("MODERN", "Modern"),
                    ("PIONEER", "Pioneer"),
                    ("STANDARD", "Standard"),
                    ("DC", "Duel Commander"),
                ],
                max_length=10,
            ),
        ),
    ]
