# Generated by Django 4.1.3 on 2023-02-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0009_alter_event_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="decklists_url",
            field=models.URLField(
                blank=True,
                help_text="A link to a page containing decklists for the event, for example mtgtop8",
                null=True,
                verbose_name="Decklists URL",
            ),
        ),
    ]
