# Generated by Django 4.1.3 on 2023-03-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0011_playeralias"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playeralias",
            options={"verbose_name_plural": "player aliases"},
        ),
    ]
