# Generated by Django 4.1.3 on 2023-03-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0012_alter_playeralias_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="eventplayerresult",
            index=models.Index(fields=["event"], name="championshi_event_i_f1cc30_idx"),
        ),
    ]
