# Generated by Django 4.1.1 on 2023-06-05 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("championship", "0013_eventplayerresult_championshi_event_i_f1cc30_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventorganizer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
