# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 4.1.7 on 2023-06-29 20:05

from django.db import migrations, models

import django_bleach.models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0014_alter_eventorganizer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=django_bleach.models.BleachField(
                blank=True,
                help_text="Supports the following HTML tags: a, b, blockquote, em, i, li, ol, p, strong, ul",
            ),
        ),
    ]
