# Generated by Django 4.1.7 on 2023-06-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0016_eventorganizer_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventorganizer",
            name="region",
            field=models.CharField(
                choices=[
                    ("AG", "Aargau"),
                    ("AR", "Appenzell Ausserrhoden"),
                    ("AI", "Appenzell Innerrhoden"),
                    ("BL", "Basel-Landschaft"),
                    ("BS", "Basel-Stadt"),
                    ("BE", "Bern"),
                    ("FR", "Fribourg"),
                    ("GE", "Genève"),
                    ("GL", "Glarus"),
                    ("GR", "Graubünden"),
                    ("JU", "Jura"),
                    ("LU", "Luzern"),
                    ("NE", "Neuchâtel"),
                    ("NW", "Nidwalden"),
                    ("OW", "Obwalden"),
                    ("SH", "Schaffhausen"),
                    ("SZ", "Schwyz"),
                    ("SO", "Solothurn"),
                    ("SG", "Sankt Gallen"),
                    ("TG", "Thurgau"),
                    ("TI", "Ticino"),
                    ("UR", "Uri"),
                    ("VS", "Valais"),
                    ("VD", "Vaud"),
                    ("ZG", "Zug"),
                    ("ZH", "Zürich"),
                    ("FR_DE", "Freiburg im Breisgau (DE)"),
                ],
                default="ZH",
                help_text="The main region where your events are held",
                max_length=5,
            ),
        ),
    ]
