# Generated by Django 4.1.7 on 2023-06-25 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0016_eventorganizer_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(max_length=255)),
                ("street_address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=10)),
                ("country", models.CharField(default="Switzerland", max_length=255)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("AG", "Aargau"),
                            ("AR", "Appenzell Ausserrhoden"),
                            ("AI", "Appenzell Innerrhoden"),
                            ("BL", "Basel-Landschaft"),
                            ("BS", "Basel-Stadt"),
                            ("BE", "Bern"),
                            ("FR", "Fribourg"),
                            ("GE", "Genève"),
                            ("GL", "Glarus"),
                            ("GR", "Graubünden"),
                            ("JU", "Jura"),
                            ("LU", "Luzern"),
                            ("NE", "Neuchâtel"),
                            ("NW", "Nidwalden"),
                            ("OW", "Obwalden"),
                            ("SH", "Schaffhausen"),
                            ("SZ", "Schwyz"),
                            ("SO", "Solothurn"),
                            ("SG", "Sankt Gallen"),
                            ("TG", "Thurgau"),
                            ("TI", "Ticino"),
                            ("UR", "Uri"),
                            ("VS", "Valais"),
                            ("VD", "Vaud"),
                            ("ZG", "Zug"),
                            ("ZH", "Zürich"),
                            ("FR_DE", "Freiburg im Breisgau (DE)"),
                        ],
                        default="ZH",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="eventorganizer",
            name="addresses",
            field=models.ManyToManyField(
                related_name="organizers", to="championship.address"
            ),
        ),
        migrations.AddField(
            model_name="eventorganizer",
            name="default_address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="championship.address",
            ),
        ),
    ]
