# Generated by Django 4.1.7 on 2023-06-25 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0017_address_eventorganizer_addresses_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventorganizer",
            name="addresses",
            field=models.ManyToManyField(
                blank=True, related_name="organizers", to="championship.address"
            ),
        ),
        migrations.AlterField(
            model_name="eventorganizer",
            name="default_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="championship.address",
            ),
        ),
    ]
