# Generated by Django 4.1.7 on 2023-10-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0019_eventplayerresult_migrate_from_points_to_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="format",
            field=models.CharField(
                choices=[
                    ("LEGACY", "Legacy"),
                    ("LIMITED", "Limited"),
                    ("MODERN", "Modern"),
                    ("PIONEER", "Pioneer"),
                    ("STANDARD", "Standard"),
                    ("DC", "Duel Commander"),
                    ("PAUPER", "Pauper"),
                    ("OS", "Old School"),
                    ("PM", "Premodern"),
                ],
                max_length=10,
            ),
        ),
    ]
