# Generated by Django 4.1.7 on 2023-10-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0020_alter_event_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
