# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 4.1.7 on 2023-11-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0020_alter_event_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.TimeField(
                blank=True,
                help_text="Approximate time when the event ends (optional)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="start_time",
            field=models.TimeField(
                blank=True, help_text="Time when the event begins (optional)", null=True
            ),
        ),
    ]
