# Generated by Django 4.1.7 on 2023-11-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0020_alter_event_format"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address"},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "Event"},
        ),
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.TimeField(
                blank=True,
                help_text="Approximate time when the event ends (optional)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="start_time",
            field=models.TimeField(
                blank=True, help_text="Time when the event begins (optional)", null=True
            ),
        ),
    ]
