# Generated by Django 4.1.7 on 2023-11-03 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0021_alter_address_options_alter_event_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address"},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "Event"},
        ),
    ]
