# Generated by Django 4.1.7 on 2023-11-11 09:12

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0022_alter_address_options_alter_event_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=django_bleach.models.BleachField(
                blank=True,
                help_text="Supports the following HTML tags: a, b, em, i, li, ol, p, strong, ul, br",
            ),
        ),
        migrations.AlterField(
            model_name="eventorganizer",
            name="description",
            field=django_bleach.models.BleachField(
                blank=True,
                help_text="Supports the following HTML tags: a, b, em, i, li, ol, p, strong, ul, br",
            ),
        ),
    ]
