# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 4.1.7 on 2023-11-11 09:12

from django.db import migrations

import django_bleach.models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0022_alter_address_options_alter_event_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=django_bleach.models.BleachField(
                blank=True,
                help_text="Supports the following HTML tags: a, b, em, i, li, ol, p, strong, ul, br",
            ),
        ),
        migrations.AlterField(
            model_name="eventorganizer",
            name="description",
            field=django_bleach.models.BleachField(
                blank=True,
                help_text="Supports the following HTML tags: a, b, em, i, li, ol, p, strong, ul, br",
            ),
        ),
    ]
