# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 4.1.7 on 2023-11-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0023_alter_event_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventplayerresult",
            name="deck_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the player's deck, e.g. 'UW Control'",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="eventplayerresult",
            name="decklist_url",
            field=models.URLField(
                blank=True,
                help_text="Link to a page where the decklist of the player can be viewed.",
                null=True,
                verbose_name="Decklist Link",
            ),
        ),
    ]
