# Generated by Django 4.1.7 on 2023-11-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0023_alter_event_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventplayerresult",
            name="deck_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the player's deck, e.g. 'UW Control'",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="eventplayerresult",
            name="decklist_url",
            field=models.URLField(
                blank=True,
                help_text="Link to a page where the decklist of the player can be viewed.",
                null=True,
                verbose_name="Decklist Link",
            ),
        ),
    ]
