# Generated by Django 4.1.11 on 2023-12-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0024_eventplayerresult_deck_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="format",
            field=models.CharField(
                choices=[
                    ("LEGACY", "Legacy"),
                    ("LIMITED", "Limited"),
                    ("MODERN", "Modern"),
                    ("PIONEER", "Pioneer"),
                    ("STANDARD", "Standard"),
                    ("DC", "Duel Commander"),
                    ("PAUPER", "Pauper"),
                    ("OS", "Old School"),
                    ("PM", "Premodern"),
                    ("VINTAGE", "Vintage"),
                ],
                max_length=10,
            ),
        ),
    ]
