# Generated by Django 4.1.7 on 2023-12-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0024_eventplayerresult_deck_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="edit_deadline_extension",
            field=models.DateField(
                blank=True,
                help_text="If set, the deadline for editing results will be extended to this date. Used to make exceptions when TOs forget to enter results.",
                null=True,
            ),
        ),
    ]
