# Generated by Django 4.1.13 on 2024-01-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0025_alter_event_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="edit_deadline_override",
            field=models.DateField(
                blank=True,
                help_text="A custom deadline for editing results, e.g. when a TO requested an extension to upload their results.",
                null=True,
            ),
        ),
    ]
