# Generated by Django 4.1.13 on 2024-01-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0025_alter_event_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="edit_deadline_extension",
            field=models.DateField(
                blank=True,
                help_text="If set, the deadline for editing results will be extended to this date. Used to make exceptions when TOs forget to enter results.",
                null=True,
            ),
        ),
    ]
