# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 4.1.13 on 2024-01-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0025_alter_event_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="edit_deadline_override",
            field=models.DateField(
                blank=True,
                help_text="A custom deadline for editing results, e.g. when a TO requested an extension to upload their results.",
                null=True,
            ),
        ),
    ]
