# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 4.2.9 on 2024-02-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0028_event_include_in_invoices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("REGULAR", "SUL Regular"),
                    ("REGIONAL", "SUL Regional"),
                    ("PREMIER", "SUL Premier"),
                    ("OTHER", "Other"),
                ],
                help_text="Select 'Other' for events without Swiss rounds and multiplayer events (including Two-Headed Giant).",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="format",
            field=models.CharField(
                choices=[
                    ("LEGACY", "Legacy"),
                    ("LIMITED", "Limited"),
                    ("MODERN", "Modern"),
                    ("PIONEER", "Pioneer"),
                    ("STANDARD", "Standard"),
                    ("EDH", "Commander/EDH"),
                    ("DC", "Duel Commander"),
                    ("PAUPER", "Pauper"),
                    ("OS", "Old School"),
                    ("PM", "Premodern"),
                    ("VINTAGE", "Vintage"),
                ],
                max_length=10,
            ),
        ),
    ]
