# Generated by Django 4.2.9 on 2024-02-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0029_events_others"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An image to represent the event. Will be shown on the event details page.",
                null=True,
                upload_to="event",
            ),
        ),
    ]
