# Generated by Django 4.2.9 on 2024-02-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0030_event_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventorganizer",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An image to represent the organizer. Will be shown on the organizer details page.",
                null=True,
                upload_to="organizer",
            ),
        ),
    ]
