# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 4.2.9 on 2024-02-14 09:14

from django.core.validators import validate_image_file_extension
from django.db import migrations, models

import championship.models


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0031_eventorganizer_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Preferably in landscape orientation. Maximum size: 1.5MB. Supported formats: JPEG, PNG, WEBP.",
                null=True,
                upload_to="event",
                validators=[
                    championship.models.event_image_validator,
                    validate_image_file_extension,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="eventorganizer",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Preferably in landscape orientation or squared. Maximum size: 500KB. Supported formats: JPEG, PNG, WEBP.",
                null=True,
                upload_to="organizer",
                validators=[
                    championship.models.organizer_image_validator,
                    validate_image_file_extension,
                ],
            ),
        ),
    ]
