# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.0.4 on 2024-04-17 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0032_alter_event_image_alter_eventorganizer_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "byes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of additional byes the player receives for this result.",
                    ),
                ),
                (
                    "direct_invite",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the player receives a direct invite for this result.",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="championship.eventplayerresult",
                    ),
                ),
            ],
        ),
    ]
