# Generated by Django 5.0.4 on 2024-06-01 12:39

import championship.models
import django.core.validators
import django.db.models.deletion
import django_bleach.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0033_specialreward"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventorganizer",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="Website"),
        ),
        migrations.AlterField(
            model_name="eventorganizer",
            name="contact",
            field=models.EmailField(
                help_text="If you run SUL Regional or SUL Premier events, you will receive your incoices here.",
                max_length=254,
                verbose_name="Invoice email",
            ),
        ),
        migrations.AlterField(
            model_name="eventorganizer",
            name="default_address",
            field=models.ForeignKey(
                blank=True,
                help_text="The location of your store or the location where most of your events take place.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="championship.address",
                verbose_name="Main location",
            ),
        ),
        migrations.AlterField(
            model_name="eventorganizer",
            name="description",
            field=django_bleach.models.BleachField(
                blank=True,
                help_text="Describe your organization to the players. You can also provide links to join your group chats or follow you on social media. Supports the following HTML tags: a, b, em, i, li, ol, p, strong, ul, br",
            ),
        ),
        migrations.AlterField(
            model_name="eventorganizer",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Preferably in landscape orientation or squared. Maximum size: 500KB. Supported formats: JPEG, PNG, WEBP.",
                null=True,
                upload_to="organizer",
                validators=[
                    championship.models.organizer_image_validator,
                    django.core.validators.validate_image_file_extension,
                ],
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="eventorganizer",
            name="name",
            field=models.CharField(
                max_length=200, verbose_name="Association/Store name"
            ),
        ),
    ]
