# Generated by Django 5.0.4 on 2024-06-02 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "championship",
            "0034_eventorganizer_url_alter_eventorganizer_contact_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="The last date on which this event will be held."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecurrenceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exception",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this rule is an exception where the event doesn't take place.",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("MO", "Monday"),
                            ("TU", "Tuesday"),
                            ("WE", "Wednesday"),
                            ("TH", "Thursday"),
                            ("FR", "Friday"),
                            ("SA", "Saturday"),
                            ("SU", "Sunday"),
                        ],
                        default="FR",
                        help_text="The weekday your event will take place.",
                        max_length=2,
                    ),
                ),
                (
                    "week_of_month",
                    models.CharField(
                        choices=[
                            ("F_1", "First"),
                            ("F_2", "Second"),
                            ("L_2", "Second last"),
                            ("L_1", "Last"),
                            ("EV", "Every week"),
                        ],
                        default="F_1",
                        help_text="Which week of the month your event will take place.",
                        max_length=3,
                    ),
                ),
                (
                    "recurring_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="championship.recurringevent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="recurring_event",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="championship.recurringevent",
            ),
        ),
    ]
