# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.0.4 on 2024-06-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "championship",
            "0036_alter_recurrencerule_type_alter_recurrencerule_week_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringevent",
            name="name",
            field=models.CharField(
                default="Event Series",
                help_text="The name of this event series, e.g. 'Modern League Q1'",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
