# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.0.4 on 2024-06-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0037_recurringevent_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="format",
            field=models.CharField(
                choices=[
                    ("LIMITED", "Limited"),
                    ("MODERN", "Modern"),
                    ("LEGACY", "Legacy"),
                    ("PIONEER", "Pioneer"),
                    ("STANDARD", "Standard"),
                    ("EDH", "Commander/EDH"),
                    ("DC", "Duel Commander"),
                    ("PAUPER", "Pauper"),
                    ("OS", "Old School"),
                    ("PM", "Premodern"),
                    ("VINTAGE", "Vintage"),
                    ("MULTI", "Multi-Format"),
                ],
                max_length=10,
            ),
        ),
    ]
