# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.0.4 on 2024-07-19 11:47

import django.db.models.deletion
from django.db import migrations, models

import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0040_alter_recurringevent_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizerLeague",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("LIMITED", "Limited"),
                            ("MODERN", "Modern"),
                            ("LEGACY", "Legacy"),
                            ("PIONEER", "Pioneer"),
                            ("STANDARD", "Standard"),
                            ("EDH", "Commander/EDH"),
                            ("DC", "Duel Commander"),
                            ("PAUPER", "Pauper"),
                            ("OS", "Old School"),
                            ("PM", "Premodern"),
                            ("VINTAGE", "Vintage"),
                            ("MULTI", "Multi-Format"),
                            ("ALL", "All Formats"),
                        ],
                        default="ALL",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("REGULAR", "SUL Regular"),
                            ("REGIONAL", "SUL Regional"),
                            ("PREMIER", "SUL Premier"),
                        ],
                        default="REGIONAL",
                        help_text="Events of the selected event type and lower will be included in the league leaderboard. We recommend excluding SUL Premier events, as they dominate leaderboards.",
                        max_length=10,
                        verbose_name="Highest category",
                    ),
                ),
                (
                    "playoffs",
                    models.BooleanField(
                        default=True,
                        help_text="Whether events with playoffs should be included in the league leaderboard.",
                        verbose_name="Include playoffs",
                    ),
                ),
                (
                    "description",
                    django_bleach.models.BleachField(
                        blank=True,
                        help_text="Describe the prize pool and other info. Supports the following HTML tags: a, b, em, i, li, ol, p, strong, ul, br",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="championship.eventorganizer",
                    ),
                ),
            ],
        ),
    ]
