# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.0.4 on 2024-11-01 18:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import championship.models


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0042_rename_eventplayerresult_to_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pronouns",
                    models.CharField(
                        choices=[
                            ("HE_HIM", "He/Him"),
                            ("SHE_HER", "She/Her"),
                            ("THEY_THEM", "They/Them"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="HE_HIM",
                        max_length=20,
                    ),
                ),
                ("custom_pronouns", models.CharField(blank=True, max_length=20)),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Note we will only show your age.",
                        null=True,
                    ),
                ),
                (
                    "hometown",
                    models.CharField(
                        blank=True,
                        help_text="Where do you currently live?",
                        max_length=200,
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, help_text="What's your job title?", max_length=200
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Some more info about you: hobbies, favorite cards/decks, fun facts, jokes, ...",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Preferably in portrait orientation. Maximum size: 1.5MB. Supported formats: JPEG, PNG, WEBP.",
                        null=True,
                        upload_to="player_profile",
                        validators=[
                            championship.models.player_image_validator,
                            django.core.validators.validate_image_file_extension,
                        ],
                        verbose_name="Logo",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="championship.player",
                    ),
                ),
            ],
        ),
    ]
