# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.0.4 on 2024-11-02 11:01

import django.core.validators
from django.db import migrations, models

import championship.models


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0043_playerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="consent_for_stream",
            field=models.BooleanField(
                default=False,
                help_text="I agree to have my player profile shown on streams.",
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="consent_for_website",
            field=models.BooleanField(
                default=False,
                help_text="I agree to have my player profile published on the website.",
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("ARCHIVED", "Archived"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="team_name",
            field=models.CharField(
                blank=True,
                help_text="This year we form teams of 3-4 players. The best 3 swiss scores of each team will be added up. The best teams will receive a small prize. If you don't have a team yet, you can leave this field empty and we will assign a team to you.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Preferably in portrait orientation. Maximum size: 500KB. Supported formats: JPEG, PNG, WEBP.",
                null=True,
                upload_to="player_profile",
                validators=[
                    championship.models.player_image_validator,
                    django.core.validators.validate_image_file_extension,
                ],
                verbose_name="Portrait photo of yourself",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="pronouns",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HE_HIM", "He/Him"),
                    ("SHE_HER", "She/Her"),
                    ("THEY_THEM", "They/Them"),
                    ("CUSTOM", "Custom"),
                ],
                max_length=20,
            ),
        ),
    ]
