# Generated by Django 5.0.4 on 2024-11-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0043_playerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="consent_for_stream",
            field=models.BooleanField(
                default=False,
                help_text="I agree to have my player profile shown on streams.",
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="consent_for_website",
            field=models.BooleanField(
                default=False,
                help_text="I agree to have my player profile published on the website.",
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("ARCHIVED", "Archived"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="pronouns",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HE_HIM", "He/Him"),
                    ("SHE_HER", "She/Her"),
                    ("THEY_THEM", "They/Them"),
                    ("CUSTOM", "Custom"),
                ],
                max_length=20,
            ),
        ),
    ]
