# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.0.4 on 2024-11-07 10:47

import django.core.validators
from django.db import migrations, models

import championship.models


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0045_alter_result_decklist_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerprofile",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Preferably in portrait orientation. Maximum size: 1MB. Supported formats: JPEG, PNG, WEBP.",
                null=True,
                upload_to="player_profile",
                validators=[
                    championship.models.player_image_validator,
                    django.core.validators.validate_image_file_extension,
                ],
                verbose_name="Portrait photo of yourself",
            ),
        ),
    ]
