# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.0.4 on 2024-12-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0052_alter_eventorganizer_default_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("REGULAR", "Regular"),
                    ("REGIONAL", "Regional"),
                    ("PREMIER", "Premier"),
                    ("NATIONAL", "National"),
                    ("QUALIFIER", "Qualifier"),
                    ("GRAND_PRIX", "Grand Prix"),
                    ("OTHER", "Other"),
                ],
                help_text="Select 'Other' for events without results.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="organizerleague",
            name="category",
            field=models.CharField(
                choices=[
                    ("REGULAR", "Regular"),
                    ("REGIONAL", "Regional"),
                    ("PREMIER", "Premier"),
                ],
                default="REGIONAL",
                help_text="Events of the selected event type and lower will be included in the league leaderboard. We recommend excluding SUL Premier events, as they dominate leaderboards.",
                max_length=10,
                verbose_name="Highest category",
            ),
        ),
    ]
