# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.0.4 on 2024-12-19 16:17

from django.db import migrations, models

import django_bleach.models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0054_playerseasondata_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NationalLeaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "season_slug",
                    models.CharField(
                        choices=[
                            ("eu2025", "Season 2025"),
                            ("eu2024mockup", "Mockup Season 2024"),
                        ],
                        max_length=50,
                        verbose_name="Season",
                    ),
                ),
                (
                    "national_invites",
                    models.IntegerField(
                        default=0,
                        help_text="How many players qualify for the National Championships from this leaderboard.",
                    ),
                ),
                (
                    "continental_invites",
                    models.IntegerField(
                        default=1,
                        help_text="How many players qualify for the continental championship, e.g. European Magic Cup.",
                    ),
                ),
                (
                    "description",
                    django_bleach.models.BleachField(
                        blank=True,
                        help_text="Additional info about the leaderboard. Supports the following HTML tags: a, b, em, i, li, ol, p, strong, ul, br",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="playerseasondata",
            name="season_slug",
            field=models.CharField(
                choices=[
                    ("eu2025", "Season 2025"),
                    ("eu2024mockup", "Mockup Season 2024"),
                ],
                max_length=50,
                verbose_name="Season",
            ),
        ),
        migrations.AddConstraint(
            model_name="nationalleaderboard",
            constraint=models.UniqueConstraint(
                fields=("country", "season_slug"), name="unique_country_season"
            ),
        ),
    ]
