# Generated by Django 4.2.1 on 2023-05-31 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="created_date",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Creation date, will be used as date in the PDF",
            ),
            preserve_default=False,
        ),
    ]
