# Generated by Django 4.2.1 on 2023-05-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0002_invoice_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment_received_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
