# Generated by Django 4.2.1 on 2023-05-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0003_invoice_payment_received_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="discount",
            field=models.IntegerField(default=0, help_text="Flat discount in CHF"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Notes about this invoice, only visible by Unity League staff.",
            ),
        ),
    ]
