# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 4.1.10 on 2023-08-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0004_invoice_discount_invoice_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="sent_date",
            field=models.DateField(
                blank=True,
                help_text="Date at which we sent the invoice to an organizer.",
                null=True,
            ),
        ),
    ]
