# Generated by Django 4.1.10 on 2023-08-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0004_invoice_discount_invoice_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="sent_date",
            field=models.DateField(
                blank=True,
                help_text="Date at which we sent the invoice to an organizer.",
                null=True,
            ),
        ),
    ]
