# Generated by Django 5.0.2 on 2024-03-17 11:38

from django.db import migrations, models

import invoicing.models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0006_payeeaddress_invoice_payee_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="frozen_file",
            field=models.FileField(
                help_text="Cached PDF output, to prevent invoices from changing once they are correct.",
                null=True,
                upload_to=invoicing.models.Invoice.frozen_file_upload_to,
            ),
        ),
    ]
