# Generated by Django 5.0.3 on 2024-04-02 13:40

from django.db import migrations, models

import invoicing.models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0007_invoice_frozen_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="frozen_file",
            field=models.FileField(
                blank=True,
                help_text="Cached PDF output, to prevent invoices from changing once they are correct.",
                null=True,
                upload_to=invoicing.models.Invoice.frozen_file_upload_to,
            ),
        ),
    ]
