# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.0.3 on 2024-04-02 13:40

from django.db import migrations, models

import invoicing.models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0007_invoice_frozen_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="frozen_file",
            field=models.FileField(
                blank=True,
                help_text="Cached PDF output, to prevent invoices from changing once they are correct.",
                null=True,
                upload_to=invoicing.models.Invoice.frozen_file_upload_to,
            ),
        ),
    ]
