# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.0.4 on 2024-04-21 19:51

from django.db import migrations, models

import decklists.models


class Migration(migrations.Migration):

    dependencies = [
        ("decklists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decklist",
            name="mainboard",
            field=models.TextField(
                help_text="Content of the main deck, one entry per line (e.g. 4 Brainstorm)",
                validators=[decklists.models.validate_decklist_format],
            ),
        ),
        migrations.AlterField(
            model_name="decklist",
            name="sideboard",
            field=models.TextField(
                help_text="Content of the sideboard, also one entry per line. If you use extra decks, such as attractions, add them here as well.",
                validators=[decklists.models.validate_decklist_format],
            ),
        ),
    ]
