# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.0.4 on 2024-11-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championship", "0046_alter_playerprofile_image"),
        ("decklists", "0003_rename_name_collection_name_override"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("submission_deadline__lte", models.F("publication_time"))
                ),
                name="decklists_collection_submission_before_publication",
                violation_error_message="Submission deadline must be before decklist publication.",
            ),
        ),
    ]
