# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.0.4 on 2024-11-17 08:54

import secrets

from django.db import migrations, models

import decklists.models


def generate_staff_key(apps, schema_editor):
    Collection = apps.get_model("decklists", "Collection")
    for row in Collection.objects.all():
        row.staff_key = secrets.token_urlsafe(nbytes=16)
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "decklists",
            "0004_collection_decklists_collection_submission_before_publication",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="staff_key",
            field=models.CharField(
                default=decklists.models.make_collection_staff_key,
                help_text="A secret string (URL safe) used to give permissions when sharing a collection link.",
                max_length=22,
            ),
        ),
        migrations.RunPython(
            generate_staff_key, reverse_code=migrations.RunPython.noop
        ),
    ]
