# Generated by Django 4.2.9 on 2024-02-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "filename",
                    models.CharField(
                        max_length=4096, primary_key=True, serialize=False
                    ),
                ),
                ("content", models.BinaryField()),
            ],
        ),
    ]
